[package]
name = "headless_pi_player"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version="1.45.0", features = [ "full" ]}
notify = "8.0.0"

thiserror = "2.0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

ctrlc = "3.4.6"